export const testPortfolio = [
    { coin: "BTC", quantity: "0.02", value: "4000" },
    { coin: "ETH", quantity: "0.0002", value: "400" },
    { coin: "LTC", quantity: "5", value: "1000" },
    { coin: "ICP", quantity: "20", value: "400" },
    { coin: "MANA", quantity: "25", value: "50" },
    { coin: "QTUM", quantity: "20.231", value: "32.312" },
];

export const orderInfo = [
    {
        coin: "BTC",
        amount: "0.02",
        position: "open",
        leverage: "2",
        status: 10,
        botName: "ArgPump#1",
    },
    {
        coin: "BTC",
        amount: "0.21",
        position: "open",
        leverage: "22",
        status: -3.2,
        botName: "ArgPump#1",
    },
    {
        coin: "ETH",
        amount: "0.03",
        position: "open",
        leverage: "1",
        status: 2,
        botName: "ArgPump#1",
    },
    {
        coin: "BTC",
        amount: "0.05",
        position: "open",
        leverage: "16",
        status: 10,
        botName: "ArgPump#1",
    },
    {
        coin: "LTC",
        amount: "0.122",
        position: "closed",
        leverage: "12",
        status: 1.46,
        botName: "ArgPump#1",
    },
    {
        coin: "QTUM",
        amount: "0.1352",
        position: "closed",
        leverage: "22",
        status: 21.3,
        botName: "ArgPump#1",
    },
    {
        coin: "MANA",
        amount: "0.1232",
        position: "closed",
        leverage: "21",
        status: 123.5,
        botName: "ArgPump#1",
    },
];

export const botInfo = [
    {
        botName: "ArgPump#1",
        startAmount: 1000.0,
        profit: 2013.23,
        openPositions: 4,
        closedPositions: 3,
        tpPercentage: 5,
        stopLossPercentage: 15,
        leverage: 2,
    },
    {
        botName: "ArgPump#2",
        startAmount: 1000.0,
        profit: -23.123,
        openPositions: 0,
        tpPercentage: 51,
        stopLossPercentage: 5,
        leverage: 4,
        closedPositions: 0,
    },
    {
        botName: "ArgPump#3",
        startAmount: 1000.0,
        profit: 13.78,
        openPositions: 0,
        tpPercentage: 51,
        stopLossPercentage: 5,
        leverage: 6,
        closedPositions: 0,
    },
    {
        botName: "ArgPump#4",
        startAmount: 1000.0,
        profit: -221.2,
        openPositions: 0,
        tpPercentage: 5,
        stopLossPercentage: 5,
        leverage: 6,
        closedPositions: 0,
    },
    {
        botName: "ArgPump#5",
        startAmount: 1000.0,
        profit: 20.0,
        openPositions: 0,
        tpPercentage: 5,
        stopLossPercentage: 5,
        leverage: 10,
        closedPositions: 0,
    },
];
